# 作者：Shen Shu 微信：书生

# Reference：https://zhuanlan.zhihu.com/p/26652400

# 完全原创，没有借鉴任何代码

In [1]:
import random
import numpy as np
import pandas as pd
import datetime

# 初始化

In [2]:
def initialize():
    global  movement_count
    movement_count=0
    print("初始化。。。")
    print("创建花色 ♥,♠,♣,♦")
    four_types=np.arange(0,400,100) # 0:♥,100:♠,200:♣,300:♦
    print("创建牌面大小")
    cards_number=np.arange(1,14,1) # 0:A, 11:J, 12:Q, 13:K
    global total_cards
    total_cards=np.array([])
    for i in four_types:
        for j in cards_number:
            total_cards=np.append(total_cards,j+i)
    cards_look=np.array(['♥ A', '♥ 2', '♥ 3', '♥ 4', '♥ 5', '♥ 6', '♥ 7', '♥ 8', '♥ 9', '♥ 10', '♥ J', '♥ Q', '♥ K', '♠ A', '♠ 2', '♠ 3', '♠ 4', '♠ 5', '♠ 6', '♠ 7', '♠ 8', '♠ 9', '♠ 10', '♠ J', '♠ Q', '♠ K', '♦ A', '♦ 2', '♦ 3', '♦ 4', '♦ 5', '♦ 6', '♦ 7', '♦ 8', '♦ 9', '♦ 10', '♦ J', '♦ Q', '♦ K', '♣ A', '♣ 2', '♣ 3', '♣ 4', '♣ 5', '♣ 6', '♣ 7', '♣ 8', '♣ 9', '♣ 10', '♣ J', '♣ Q', '♣ K'])
    cards_look.shape
    print("花色数字合并中")
    global cards_dict
    cards_dict=dict(zip(total_cards, cards_look))
    cards_dict.update({0.0: "_"}) 
    cards_dict.update({100.0:"黑桃空"})
    cards_dict.update({200.0:"方片空"})
    cards_dict.update({300.0:"草花空"})
    print(cards_dict)

In [3]:
initialize()

初始化。。。
创建花色 ♥,♠,♣,♦
创建牌面大小
花色数字合并中
{1.0: '♥ A', 2.0: '♥ 2', 3.0: '♥ 3', 4.0: '♥ 4', 5.0: '♥ 5', 6.0: '♥ 6', 7.0: '♥ 7', 8.0: '♥ 8', 9.0: '♥ 9', 10.0: '♥ 10', 11.0: '♥ J', 12.0: '♥ Q', 13.0: '♥ K', 101.0: '♠ A', 102.0: '♠ 2', 103.0: '♠ 3', 104.0: '♠ 4', 105.0: '♠ 5', 106.0: '♠ 6', 107.0: '♠ 7', 108.0: '♠ 8', 109.0: '♠ 9', 110.0: '♠ 10', 111.0: '♠ J', 112.0: '♠ Q', 113.0: '♠ K', 201.0: '♦ A', 202.0: '♦ 2', 203.0: '♦ 3', 204.0: '♦ 4', 205.0: '♦ 5', 206.0: '♦ 6', 207.0: '♦ 7', 208.0: '♦ 8', 209.0: '♦ 9', 210.0: '♦ 10', 211.0: '♦ J', 212.0: '♦ Q', 213.0: '♦ K', 301.0: '♣ A', 302.0: '♣ 2', 303.0: '♣ 3', 304.0: '♣ 4', 305.0: '♣ 5', 306.0: '♣ 6', 307.0: '♣ 7', 308.0: '♣ 8', 309.0: '♣ 9', 310.0: '♣ 10', 311.0: '♣ J', 312.0: '♣ Q', 313.0: '♣ K', 0.0: '_', 100.0: '黑桃空', 200.0: '方片空', 300.0: '草花空'}


# 洗牌并且发牌

In [4]:
def start_shuffling():
    
    np.random.shuffle(total_cards)
    global hide_cards 
    hide_cards= np.zeros(shape=(7,6))
    global show_cards 
    show_cards= np.zeros(shape=(7,13))
    temp_1=0
    print("隐藏牌堆发牌中")
    for i in range(1,7): # y轴 给隐藏牌堆发牌
        for j in range (i): # x轴
            hide_cards[i][j]=total_cards[temp_1]
            temp_1+=1
    print("下方牌堆法派中")
    for i in range(7):#给下方看得见的牌堆发牌
        show_cards[i][0]=total_cards[temp_1]
        temp_1+=1
    print("随机牌堆发牌中")
    global 随机牌堆
    随机牌堆=np.zeros(shape=(52-temp_1,))
    for i in range(len(随机牌堆)):
        随机牌堆[i]=total_cards[temp_1]
        temp_1+=1
    随机牌堆=np.sort(随机牌堆)
    print("已完成的牌堆初始化")
    global 已完成的牌堆
    已完成的牌堆=np.array([0.0,100.0,200.0,300.0])


In [5]:
start_shuffling()

隐藏牌堆发牌中
下方牌堆法派中
随机牌堆发牌中
已完成的牌堆初始化


# 数据可视化

In [6]:
#这个代码在jupternotebook上不好使，在colab上可以
def colour(x): #给pandas dataframe 上色
    if x[0]=='♥'or x[0]=='♦':
        return 'color: %s' % 'red'

In [7]:
def show_finished_cards(已完成的牌堆): # 看完成的牌堆，并且上色
    df = pd.DataFrame(已完成的牌堆).T
    for i in range(4):
        df[i]=df[i].map(lambda x:cards_dict[x])
    display(df)

In [8]:
def show_random_cards(随机牌堆): #看随机牌堆，并且上色
    df = pd.DataFrame(随机牌堆).T
    for i in range(24):
        df[i]=df[i].map(lambda x:cards_dict[x])
    display(df)

In [9]:
def show_V_style(df): #把牌面竖起来看，更接近于游戏视角
    show_to_person=np.hstack(df).T
    df = pd.DataFrame(show_to_person)
    for i in range(7):
        df[i]=df[i].map(lambda x:cards_dict[x])
    display(show_random_cards(随机牌堆))
    display(df)
    show_finished_cards(已完成的牌堆)

In [10]:
display(show_V_style((hide_cards,show_cards)))

0    1    2    3    4    5    6    7    8    9   ...    14   15   16   17  \
0  ♥ A  ♥ 5  ♥ 8  ♠ A  ♠ 2  ♠ 5  ♠ 6  ♠ 7  ♠ 9  ♠ J  ...  ♦ 10  ♦ Q  ♣ A  ♣ 2   

    18   19   20   21   22   23  
0  ♣ 3  ♣ 4  ♣ 6  ♣ 7  ♣ Q  ♣ K  

[1 rows x 24 columns]

None

0    1     2    3    4     5     6
0     _  ♣ J  ♥ 10  ♣ 8  ♥ 3   ♦ J   ♥ J
1     _    _   ♥ 4  ♥ 7  ♦ K   ♥ 6   ♣ 5
2     _    _     _  ♦ 3  ♠ K   ♥ Q   ♥ 9
3     _    _     _    _  ♦ A   ♦ 5   ♠ Q
4     _    _     _    _    _   ♠ 8  ♣ 10
5     _    _     _    _    _     _   ♦ 6
6   ♣ 9  ♠ 4   ♥ 2  ♠ 3  ♥ K  ♠ 10   ♦ 8
7     _    _     _    _    _     _     _
8     _    _     _    _    _     _     _
9     _    _     _    _    _     _     _
10    _    _     _    _    _     _     _
11    _    _     _    _    _     _     _
12    _    _     _    _    _     _     _
13    _    _     _    _    _     _     _
14    _    _     _    _    _     _     _
15    _    _     _    _    _     _     _
16    _    _     _    _    _     _     _
17    _    _     _    _    _     _     _
18    _    _     _    _    _     _     _

0    1    2    3
0  _  黑桃空  方片空  草花空

None

In [11]:
def show_H_style(df): #把牌面横过来看，方便写代码
    df = pd.DataFrame(np.hstack(df))
    for i in range(19):
        df[i]=df[i].map(lambda x:cards_dict[x])
    display(show_random_cards(随机牌堆))
    display(df)
    show_finished_cards(已完成的牌堆)

In [12]:
display(show_H_style((hide_cards,show_cards)))

0    1    2    3    4    5    6    7    8    9   ...    14   15   16   17  \
0  ♥ A  ♥ 5  ♥ 8  ♠ A  ♠ 2  ♠ 5  ♠ 6  ♠ 7  ♠ 9  ♠ J  ...  ♦ 10  ♦ Q  ♣ A  ♣ 2   

    18   19   20   21   22   23  
0  ♣ 3  ♣ 4  ♣ 6  ♣ 7  ♣ Q  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3     4    5     6  7  8  9 10 11 12 13 14 15 16 17 18
0     _    _    _    _     _    _   ♣ 9  _  _  _  _  _  _  _  _  _  _  _  _
1   ♣ J    _    _    _     _    _   ♠ 4  _  _  _  _  _  _  _  _  _  _  _  _
2  ♥ 10  ♥ 4    _    _     _    _   ♥ 2  _  _  _  _  _  _  _  _  _  _  _  _
3   ♣ 8  ♥ 7  ♦ 3    _     _    _   ♠ 3  _  _  _  _  _  _  _  _  _  _  _  _
4   ♥ 3  ♦ K  ♠ K  ♦ A     _    _   ♥ K  _  _  _  _  _  _  _  _  _  _  _  _
5   ♦ J  ♥ 6  ♥ Q  ♦ 5   ♠ 8    _  ♠ 10  _  _  _  _  _  _  _  _  _  _  _  _
6   ♥ J  ♣ 5  ♥ 9  ♠ Q  ♣ 10  ♦ 6   ♦ 8  _  _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  黑桃空  方片空  草花空

None

In [13]:
def show_origin(): #产看原始文件
    print(show_cards)
    print('-----------------------')
    print(hide_cards)

In [14]:
show_origin()

[[309.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [104.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [103.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 13.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [110.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [208.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
-----------------------
[[  0.   0.   0.   0.   0.   0.]
 [311.   0.   0.   0.   0.   0.]
 [ 10.   4.   0.   0.   0.   0.]
 [308.   7. 203.   0.   0.   0.]
 [  3. 213. 113. 201.   0.   0.]
 [211.   6.  12. 205. 108.   0.]
 [ 11. 305.   9. 112. 310. 206.]]


# 第一步，检查是否有牌能放到已完成牌堆上！

# 力所能及地去翻开下方所有在隐藏牌堆中的牌

# 只有确定能够产生意义的情况下，才将随机牌堆中的牌拖动到下方。这样的移动叫做有效移牌，反之为无效移牌。

In [15]:
def put_all_cards_in_finished_cards():
    global  movement_count
    count=True
    while count==True:
        count=False
        for i in range(7):# 检查show的牌堆最后一张能不能放上去
            for j in range(13):
                for k in range(len(已完成的牌堆)):
                    if show_cards[i][-1-j] != 0.0 and show_cards[i][-1-j]-已完成的牌堆[k]==1:
                        movement_count+=1
                        print(f"表面牌的最后一张    {cards_dict[show_cards[i][-1-j]]}   移动去已完成的牌堆里    {cards_dict[已完成的牌堆[k]]}")
                        已完成的牌堆[k]=show_cards[i][-1-j]
                        show_cards[i][-1-j]=0.0
                        count==True
                if show_cards[i][-1-j]!=0.0:
                    break #  如果最后一张牌不是空牌并且没有被放上去的时候，就不继续往前推，因为只能移动表面的一张牌
                
                    
        for i in range(len(随机牌堆)):
            for j in range(len(已完成的牌堆)):
                if 随机牌堆[i]-已完成的牌堆[j]==1:
                    count=True
                    movement_count+=1
                    print(f"随机牌堆的  {cards_dict[随机牌堆[i]]}   已经移动到了已完成牌堆的    {cards_dict[已完成的牌堆[j]]}   里面了")
                    已完成的牌堆[j]=随机牌堆[i]
                    随机牌堆[i]=0



# 第二步，开始移动下方牌堆互相移动

In [16]:
def get_top_show_cards(x): # 这步是用来取下方卡牌最顶层的牌
    temp_2=np.zeros(shape=(7,))
    for i in range(7):
        temp_2[i]=x[i][0] #只取最上方的那个排移动整个下面一串牌
    #print(list(map(lambda x: cards_dict[x],temp_2)))         
    return temp_2

In [17]:
def get_bottom_show_cards(x): # 这步是用来尾端的卡牌
    temp_6=np.zeros(shape=(7,))
    for i in range(7):
        for j in range(13):
            if x[i][-1-j]!=0.0:
                temp_6[i]=x[i][-1-j] #只取最上方的那个排移动整个下面一串牌
                
                break
    #print(list(map(lambda x: cards_dict[x],temp_6)))              
    return temp_6

# 显示可以在已经显示的牌中互相移动的牌

In [18]:
def display_move_show_cards():
    move_work=[]
    top_show_cards=get_top_show_cards(show_cards)
    bottom_show_cards=get_bottom_show_cards(show_cards)
    for i in range(7):
        for j in range(7):
            #print(top_show_cards[j]-bottom_show_cards[i],end='\t')
            if (bottom_show_cards[i]-top_show_cards[j]  in (-299,-99,101,301)) and(i!=j): #自己的头不能和自己的屁股比
                move_work.append((j,i))
                #print(f"show row {i} can move to the end of row {j}")
                print(f"普通移牌    {cards_dict[top_show_cards[j]]} 可以移动去 {cards_dict[bottom_show_cards[i]]}")


    #开始移动K 到空位
    for k in range(7):#遍历7行
        if hide_cards[k][0]==0 and show_cards[k][0]==0: #如果hide 和 show 的第k行第一个都为0
            for l in range(7):#便利7行开头找K
                if show_cards[l][0] in (13,113,213,313) and hide_cards[l][0]!=0:#如果show里面7行第一个有空位
                    move_work.append((l,k))
                    #print(f"show row {l} can move to the end of row {k}")
                    print(f"普通 K    {cards_dict[top_show_cards[l]]} 可以移动去 {cards_dict[top_show_cards[k]]}")
    #开始移动上方随机牌堆，找有效牌

    if len(move_work)==0:
        m,n=show_cards.shape
        #先找下面已经露出的两张同色同大小的牌，上面小一号，可以无脑往下放
        #先在show牌堆里面找花色一样并且大小相同的牌
        #再回随机牌堆找对应的牌
        for ii in range(m):
            for jj in range(n):
                for kk in range(m):
                    for ll in range(n):
                        if show_cards[ii][jj] !=0.0 and show_cards[kk][ll]!=0.0 and kk>ii and abs(show_cards[ii][jj]-show_cards[kk][ll]) == 200:#相同数字相同花色就是这个情况
                            for q in range(24):
                                if show_cards[ii][jj]-随机牌堆[q] in (-299,-99,101,301):
                                    print(cards_dict[随机牌堆[q]],"符合要求","下方牌堆两张同色",cards_dict[show_cards[ii][jj]],cards_dict[show_cards[kk][ll]],ii,kk,"上方随机牌堆有牌能直接放下来")
                                    for xxx in range(7):
                                        if bottom_show_cards[xxx]-随机牌堆[q] in(-299,-99,101,301):
                                            move_work.append((q+100,xxx))




    if len(move_work)==0:
        for i in range(24): #随机牌堆用
            for j in range(7): # 尾部牌堆用
                for k in range(7): #头部牌堆用
                    if (随机牌堆[i]!=0) and (bottom_show_cards[j]) !=0 and top_show_cards[k]!=0.0 and (bottom_show_cards[j]-随机牌堆[i] in (-299,-99,101,301)) and (随机牌堆[i]-top_show_cards[k] in (-299,-99,101,301)):
                        print(随机牌堆[i],bottom_show_cards[j],top_show_cards[k])
                        move_work.append((i+100,j))
                        print(f"有效随机牌： 随机牌堆中 {cards_dict[随机牌堆[i]]} 可以移动去 下方牌堆 {cards_dict[bottom_show_cards[j]]} 并且还有下方牌堆中{cards_dict[top_show_cards[k]]} 可以移动到随机牌上")
    print("有几个动作",move_work)
    if len(move_work)==0:
        print("实在找不出了，找个深度最高的放进去了，开始搜索")
        temp_10=np.array([])
        temp_10_position=np.array([])
        mmm_position=np.array([])
        for mmm in range(7):
            for i in range(24):
                if bottom_show_cards[mmm]-随机牌堆[i] in (-299,-99,101,301):
                    temp_10=np.hstack((temp_10,随机牌堆[i]))
                    temp_10_position=np.hstack((temp_10_position,i))
                    mmm_position=np.hstack((mmm_position,mmm))
                    #print(f"我是mmm_position{mmm_position}")
        if len(temp_10)!=0:
            print("随机牌堆除k以外都不能移动了")   
            temp_index1=深度搜索(temp_10)
            # print(f"深度最高的是{cards_dict[temp_10[temp_index1]]}")
            # print(temp_10_position)
            # print(mmm_position)
            # print(f"我是mmm_position[temp_index1]{mmm_position[temp_index1]}")
            # print(temp_10_position[temp_index1]+100,mmm_position[temp_index1])
            move_work.append((int(temp_10_position[temp_index1]+100),int(mmm_position[temp_index1])))
            print(move_work)
        elif len(temp_10)==0:
            print("随机牌堆除k以外都不能移动了")
            #开始移动K
            for ik in range(24):
                if 随机牌堆[ik] in (13,113,213,313):
                    for jk in range(7):
                        if hide_cards[jk][0]==0 and show_cards[jk][0]==0:
                            move_work.append((ik+100,jk))
            if len(move_work)>1:
                temp_10=np.array([])

                for im in range(len(move_work)):
                    temp_10=np.hstack((temp_10,随机牌堆[move_work[im][0]-100]))
                
                move_work=[move_work[深度搜索(temp_10)]]


    return move_work

In [19]:
def 深度搜索(temp_10):#进去是一个包含随机牌的数组，出来是这个数组最有深度的数组index
    cards_can_move_temp=np.hstack((get_top_show_cards(show_cards),随机牌堆))
    cards_can_move_temp
    trigger=True
    origin_temp_10=temp_10.copy()
    temp_10_deep=np.zeros(shape=(temp_10.shape))
    for aaa in range(len(temp_10)): # 可以放下来的牌
        print(f"第{aaa}个-------------")
        while trigger:
            trigger=False
            for qqqq in range(len(cards_can_move_temp)): #全部牌搜索
                if temp_10[aaa]-cards_can_move_temp[qqqq] in (-299,-99,101,301):
                    print(cards_dict[cards_can_move_temp[qqqq]])
                    temp_10_deep[aaa]+=1
                    temp_10[aaa]=cards_can_move_temp[qqqq]
                    trigger=True
                    break
    print(dict(zip(map(lambda x :cards_dict[x],origin_temp_10),temp_10_deep)))
    #print(temp_10_deep)
    #print(np.where(temp_10_deep==np.max(temp_10_deep)))
    return np.where(temp_10_deep==np.max(temp_10_deep))[0][0]

#print(temp_10_deep)

# **下面会产生分歧点** 暂时不考虑，就按搜到的顺序进行


In [20]:
def move_show_cards():
    global  movement_count
    move_work=display_move_show_cards()
    if len(move_work)==0:
        print("没有可以移动的了")
        return "No_moves_anymore"
    #print(move_work[0])
    if move_work[0][0]<100:
        for i in range(13):
            if show_cards[move_work[0][0]][i]==0.0:
                show_cards_move_from_index=i#有问题，这个是用来做结尾用的，前面的都得挪走       
                break
    for j in range(13):
        if show_cards[move_work[0][1]][j]==0.0:
            show_cards_move_to_index=j
            break
    if move_work[0][0]<100:
        #print(f"show_cards_move_from_index:{show_cards_move_from_index}")
        #print(f"show_cards_move_to_index:{show_cards_move_to_index}")
        #print(f"from 0:{show_cards_move_from_index} to {show_cards_move_to_index}:{show_cards_move_to_index+len(show_cards[move_work[0][0]][0:show_cards_move_from_index])}")
        show_cards[move_work[0][1]][show_cards_move_to_index:show_cards_move_to_index+len(show_cards[move_work[0][0]][0:show_cards_move_from_index])]=show_cards[move_work[0][0]][0:show_cards_move_from_index]#从to的那一列的空头到from那头的长度=from的那一列的从头到空格那里
        movement_count+=1
        print(f"把solt {move_work[0][0]} 上的牌堆{list(map(lambda x:cards_dict[x],show_cards[move_work[0][0]][0:show_cards_move_from_index]))} 移动到了 slot {move_work[0][1]} 上牌{cards_dict[show_cards[move_work[0][1]][show_cards_move_to_index-1]]}")
        show_cards[move_work[0][0]][0:show_cards_move_from_index]=np.zeros(shape=show_cards[move_work[0][0]][0:show_cards_move_from_index].shape)
    elif move_work[0][0]>=100:
        print("移动随机牌堆里的牌")
        print(f"随机牌堆的{cards_dict[随机牌堆[move_work[0][0]-100]]},移动到下方牌堆slot{move_work[0][1]} 的牌 {cards_dict[show_cards[move_work[0][1]][show_cards_move_to_index-1]]} 上")
        movement_count+=1
        show_cards[move_work[0][1]][show_cards_move_to_index]=随机牌堆[move_work[0][0]-100]
        随机牌堆[move_work[0][0]-100]=0.0



# 检查show空的那行后面的隐藏牌有没有出来

In [21]:
def move_hide_to_show_cards(): 
    global  movement_count
    for i in range(7):
        if show_cards[i][0]==0:
            for j in range(6):
                if hide_cards[i][-1-j]!=0.0:
                    print(f"把hide里的 slot{i}最外一张  {cards_dict[hide_cards[i][-1-j]]}  移动到了show的最上面一张 {cards_dict[show_cards[i][0]]}")
                    movement_count+=1
                    show_cards[i][0]=hide_cards[i][-1-j]
                    hide_cards[i][-1-j]=0.0
                    break


In [22]:
winrate=[]
times=100
starttime = datetime.datetime.now()
for i in range(times):
    initialize()
    start_shuffling()
    while True:
        global  movement_count
        movement_count=0
        put_all_cards_in_finished_cards()
        move_hide_to_show_cards()
        move_show_cards()
        move_hide_to_show_cards()
        if sum(已完成的牌堆)==652.0:
            print("游戏成功")
            winrate.append(1)
            break
        elif movement_count==0:
            print("游戏失败")
            winrate.append(0)
            #display(show_H_style((hide_cards,show_cards)))

            break
endtime = datetime.datetime.now()
print (endtime - starttime)

初始化。。。
创建花色 ♥,♠,♣,♦
创建牌面大小
花色数字合并中
{1.0: '♥ A', 2.0: '♥ 2', 3.0: '♥ 3', 4.0: '♥ 4', 5.0: '♥ 5', 6.0: '♥ 6', 7.0: '♥ 7', 8.0: '♥ 8', 9.0: '♥ 9', 10.0: '♥ 10', 11.0: '♥ J', 12.0: '♥ Q', 13.0: '♥ K', 101.0: '♠ A', 102.0: '♠ 2', 103.0: '♠ 3', 104.0: '♠ 4', 105.0: '♠ 5', 106.0: '♠ 6', 107.0: '♠ 7', 108.0: '♠ 8', 109.0: '♠ 9', 110.0: '♠ 10', 111.0: '♠ J', 112.0: '♠ Q', 113.0: '♠ K', 201.0: '♦ A', 202.0: '♦ 2', 203.0: '♦ 3', 204.0: '♦ 4', 205.0: '♦ 5', 206.0: '♦ 6', 207.0: '♦ 7', 208.0: '♦ 8', 209.0: '♦ 9', 210.0: '♦ 10', 211.0: '♦ J', 212.0: '♦ Q', 213.0: '♦ K', 301.0: '♣ A', 302.0: '♣ 2', 303.0: '♣ 3', 304.0: '♣ 4', 305.0: '♣ 5', 306.0: '♣ 6', 307.0: '♣ 7', 308.0: '♣ 8', 309.0: '♣ 9', 310.0: '♣ 10', 311.0: '♣ J', 312.0: '♣ Q', 313.0: '♣ K', 0.0: '_', 100.0: '黑桃空', 200.0: '方片空', 300.0: '草花空'}
隐藏牌堆发牌中
下方牌堆法派中
随机牌堆发牌中
已完成的牌堆初始化
表面牌的最后一张    ♠ A   移动去已完成的牌堆里    黑桃空
随机牌堆的  ♥ A   已经移动到了已完成牌堆的    _   里面了
随机牌堆的  ♠ 2   已经移动到了已完成牌堆的    ♠ A   里面了
随机牌堆的  ♦ A   已经移动到了已完成牌堆的    方片空   里面了
表面牌的最后一张    ♠ 3  

In [23]:
print(f"{times} 次测试中的成功率为： {sum(winrate)/times*100}%")
print(f"{times} 次 总用时为{(endtime - starttime).seconds}秒")

100 次测试中的成功率为： 27.0%
100 次 总用时为7秒


# 运行这个一次可以看到可视化

In [34]:
initialize()
start_shuffling()
while True:
    global  movement_count
    movement_count=0
    display(show_H_style((hide_cards,show_cards)))
    put_all_cards_in_finished_cards()
    move_hide_to_show_cards()
    move_show_cards()
    move_hide_to_show_cards()
    if sum(已完成的牌堆)==652.0:
        display(show_H_style((hide_cards,show_cards)))
        print("游戏成功")
        break
    elif movement_count==0:
        display(show_H_style((hide_cards,show_cards)))
        print("游戏失败")      
        break

初始化。。。
创建花色 ♥,♠,♣,♦
创建牌面大小
花色数字合并中
{1.0: '♥ A', 2.0: '♥ 2', 3.0: '♥ 3', 4.0: '♥ 4', 5.0: '♥ 5', 6.0: '♥ 6', 7.0: '♥ 7', 8.0: '♥ 8', 9.0: '♥ 9', 10.0: '♥ 10', 11.0: '♥ J', 12.0: '♥ Q', 13.0: '♥ K', 101.0: '♠ A', 102.0: '♠ 2', 103.0: '♠ 3', 104.0: '♠ 4', 105.0: '♠ 5', 106.0: '♠ 6', 107.0: '♠ 7', 108.0: '♠ 8', 109.0: '♠ 9', 110.0: '♠ 10', 111.0: '♠ J', 112.0: '♠ Q', 113.0: '♠ K', 201.0: '♦ A', 202.0: '♦ 2', 203.0: '♦ 3', 204.0: '♦ 4', 205.0: '♦ 5', 206.0: '♦ 6', 207.0: '♦ 7', 208.0: '♦ 8', 209.0: '♦ 9', 210.0: '♦ 10', 211.0: '♦ J', 212.0: '♦ Q', 213.0: '♦ K', 301.0: '♣ A', 302.0: '♣ 2', 303.0: '♣ 3', 304.0: '♣ 4', 305.0: '♣ 5', 306.0: '♣ 6', 307.0: '♣ 7', 308.0: '♣ 8', 309.0: '♣ 9', 310.0: '♣ 10', 311.0: '♣ J', 312.0: '♣ Q', 313.0: '♣ K', 0.0: '_', 100.0: '黑桃空', 200.0: '方片空', 300.0: '草花空'}
隐藏牌堆发牌中
下方牌堆法派中
随机牌堆发牌中
已完成的牌堆初始化


0    1    2    3     4    5    6    7    8    9   ...   14   15   16   17  \
0  ♥ 3  ♥ 4  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  ♠ A  ♠ 2  ...  ♦ A  ♦ 3  ♦ 4  ♦ 5   

     18   19   20    21   22   23  
0  ♦ 10  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4    5    6  7  8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _    _  ♦ 9  _  _  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _    _  ♣ Q  _  _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _    _  ♥ 8  _  _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _    _  ♠ K  _  _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7  ♦ 8  ♥ 7    _    _  ♣ A  _  _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  ♣ 5  ♠ 7    _  ♣ 8  _  _  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  ♥ 2  ♣ 3  _  _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  黑桃空  方片空  草花空

None

表面牌的最后一张    ♣ A   移动去已完成的牌堆里    草花空
随机牌堆的  ♠ A   已经移动到了已完成牌堆的    黑桃空   里面了
随机牌堆的  ♠ 2   已经移动到了已完成牌堆的    ♠ A   里面了
随机牌堆的  ♦ A   已经移动到了已完成牌堆的    方片空   里面了
把hide里的 slot4最外一张  ♥ 7  移动到了show的最上面一张 _
普通移牌    ♣ 8 可以移动去 ♦ 9
普通移牌    ♥ 7 可以移动去 ♣ 8
有几个动作 [(5, 0), (4, 5)]
把solt 5 上的牌堆['♣ 8'] 移动到了 slot 0 上牌♦ 9
把hide里的 slot5最外一张  ♠ 7  移动到了show的最上面一张 _


0    1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  ♥ 4  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4    5    6    7  8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _    _  ♦ 9  ♣ 8  _  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _    _  ♣ Q    _  _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _    _  ♥ 8    _  _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _    _  ♠ K    _  _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7  ♦ 8    _    _    _  ♥ 7    _  _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  ♣ 5    _    _  ♠ 7    _  _  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  ♥ 2  ♣ 3    _  _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

普通移牌    ♥ 7 可以移动去 ♣ 8
普通移牌    ♠ 7 可以移动去 ♥ 8
有几个动作 [(4, 0), (5, 2)]
把solt 4 上的牌堆['♥ 7'] 移动到了 slot 0 上牌♣ 8
把hide里的 slot4最外一张  ♦ 8  移动到了show的最上面一张 _


0    1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  ♥ 4  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4    5    6    7    8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _    _  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _    _  ♣ Q    _    _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _    _  ♥ 8    _    _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _    _  ♠ K    _    _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _    _    _    _  ♦ 8    _    _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  ♣ 5    _    _  ♠ 7    _    _  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  ♥ 2  ♣ 3    _    _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

普通移牌    ♠ 7 可以移动去 ♥ 8
普通移牌    ♠ 7 可以移动去 ♦ 8
有几个动作 [(5, 2), (5, 4)]
把solt 5 上的牌堆['♠ 7'] 移动到了 slot 2 上牌♥ 8
把hide里的 slot5最外一张  ♣ 5  移动到了show的最上面一张 _


0    1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  ♥ 4  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4    5    6    7    8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _    _  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _    _  ♣ Q    _    _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _    _  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _    _  ♠ K    _    _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _    _    _    _  ♦ 8    _    _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8    _    _    _  ♣ 5    _    _  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  ♥ 2  ♣ 3    _    _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

4.0 305.0 303.0
有效随机牌： 随机牌堆中 ♥ 4 可以移动去 下方牌堆 ♣ 5 并且还有下方牌堆中♣ 3 可以移动到随机牌上
6.0 107.0 305.0
有效随机牌： 随机牌堆中 ♥ 6 可以移动去 下方牌堆 ♠ 7 并且还有下方牌堆中♣ 5 可以移动到随机牌上
204.0 305.0 303.0
有效随机牌： 随机牌堆中 ♦ 4 可以移动去 下方牌堆 ♣ 5 并且还有下方牌堆中♣ 3 可以移动到随机牌上
有几个动作 [(101, 5), (102, 2), (116, 5)]
移动随机牌堆里的牌
随机牌堆的♥ 4,移动到下方牌堆slot5 的牌 ♣ 5 上


0  1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4    5    6    7    8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _    _  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _    _  ♣ Q    _    _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _    _  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _    _  ♠ K    _    _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _    _    _    _  ♦ 8    _    _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8    _    _    _  ♣ 5  ♥ 4    _  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  ♥ 2  ♣ 3    _    _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

普通移牌    ♣ 3 可以移动去 ♥ 4
有几个动作 [(6, 5)]
把solt 6 上的牌堆['♣ 3'] 移动到了 slot 5 上牌♥ 4
把hide里的 slot6最外一张  ♥ 2  移动到了show的最上面一张 _


0  1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3    4  5    6    7    8  9 10 11 12 13 14 15 16 17 18
0    _    _    _    _    _  _  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _    _  _  ♣ Q    _    _  _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _    _  _  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _    _  _  ♠ K    _    _  _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _    _    _  _  ♦ 8    _    _  _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8    _    _  _  ♣ 5  ♥ 4  ♣ 3  _  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  ♠ 3  _  ♥ 2    _    _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

普通移牌    ♥ 2 可以移动去 ♣ 3
有几个动作 [(6, 5)]
把solt 6 上的牌堆['♥ 2'] 移动到了 slot 5 上牌♣ 3
把hide里的 slot6最外一张  ♠ 3  移动到了show的最上面一张 _


0  1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2    3  4  5    6    7    8    9 10 11 12 13 14 15 16 17 18
0    _    _    _    _  _  _  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _    _  _  _  ♣ Q    _    _    _  _  _  _  _  _  _  _  _  _
2  ♥ 5  ♣ 7    _    _  _  _  ♥ 8  ♠ 7    _    _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5    _  _  _  ♠ K    _    _    _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _    _  _  _  ♦ 8    _    _    _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8    _  _  _  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  ♠ 9  _  _  ♠ 3    _    _    _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 2  ♦ A  ♣ A

None

表面牌的最后一张    ♠ 3   移动去已完成的牌堆里    ♠ 2
随机牌堆的  ♠ 4   已经移动到了已完成牌堆的    ♠ 3   里面了
把hide里的 slot6最外一张  ♠ 9  移动到了show的最上面一张 _
普通移牌    ♥ 8 可以移动去 ♠ 9
普通移牌    ♦ 8 可以移动去 ♠ 9
有几个动作 [(2, 6), (4, 6)]
把solt 2 上的牌堆['♥ 8', '♠ 7'] 移动到了 slot 6 上牌♠ 9
把hide里的 slot2最外一张  ♣ 7  移动到了show的最上面一张 _


0  1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8    9 10 11 12 13 14 15 16 17 18
0    _    _    _  _  _  _  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _  _  _  _  ♣ Q    _    _    _  _  _  _  _  _  _  _  _  _
2  ♥ 5    _    _  _  _  _  ♣ 7    _    _    _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _    _    _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8    _    _    _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  _  _  _  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

普通移牌    ♣ 7 可以移动去 ♦ 8
有几个动作 [(2, 4)]
把solt 2 上的牌堆['♣ 7'] 移动到了 slot 4 上牌♦ 8
把hide里的 slot2最外一张  ♥ 5  移动到了show的最上面一张 _


0  1    2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  ♥ 6  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8    9 10 11 12 13 14 15 16 17 18
0    _    _    _  _  _  _  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _  _  _  _  ♣ Q    _    _    _  _  _  _  _  _  _  _  _  _
2    _    _    _  _  _  _  ♥ 5    _    _    _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _    _    _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7    _    _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  _  _  _  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

♥ 6 符合要求 下方牌堆两张同色 ♣ 7 ♠ 7 4 6 上方随机牌堆有牌能直接放下来
有几个动作 [(102, 4), (102, 6)]
移动随机牌堆里的牌
随机牌堆的♥ 6,移动到下方牌堆slot4 的牌 ♣ 7 上


0  1  2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8    9 10 11 12 13 14 15 16 17 18
0    _    _    _  _  _  _  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _  _  _  _  _
1  ♥ A    _    _  _  _  _  ♣ Q    _    _    _  _  _  _  _  _  _  _  _  _
2    _    _    _  _  _  _  ♥ 5    _    _    _  _  _  _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _    _    _  _  _  _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6    _  _  _  _  _  _  _  _  _  _
5  ♦ 2  ♣ 2  ♠ 8  _  _  _  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7    _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

普通移牌    ♣ 5 可以移动去 ♥ 6
有几个动作 [(5, 4)]
把solt 5 上的牌堆['♣ 5', '♥ 4', '♣ 3', '♥ 2'] 移动到了 slot 4 上牌♥ 6
把hide里的 slot5最外一张  ♠ 8  移动到了show的最上面一张 _


0  1  2    3     4    5    6    7  8  9   ... 14   15   16   17    18  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  ♥ J  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10   

    19   20    21   22   23  
0  ♦ J  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8    9   10   11   12 13 14 15 16 17 18
0    _    _    _  _  _  _  ♦ 9  ♣ 8  ♥ 7    _    _    _    _  _  _  _  _  _  _
1  ♥ A    _    _  _  _  _  ♣ Q    _    _    _    _    _    _  _  _  _  _  _  _
2    _    _    _  _  _  _  ♥ 5    _    _    _    _    _    _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _    _    _    _    _    _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _    _    _    _    _    _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7    _    _    _    _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

有几个动作 []
实在找不出了，找个深度最高的放进去了，开始搜索
随机牌堆除k以外都不能移动了
第0个-------------
♠ 10
♦ 9
♠ 8
第1个-------------
第2个-------------
第3个-------------
{'♥ J': 3.0, '♦ J': 0.0, '♥ Q': 0.0, '♦ Q': 0.0}
[(105, 1)]
移动随机牌堆里的牌
随机牌堆的♥ J,移动到下方牌堆slot1 的牌 ♣ Q 上


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8    9   10   11   12 13 14 15 16 17 18
0    _    _    _  _  _  _  ♦ 9  ♣ 8  ♥ 7    _    _    _    _  _  _  _  _  _  _
1  ♥ A    _    _  _  _  _  ♣ Q  ♥ J    _    _    _    _    _  _  _  _  _  _  _
2    _    _    _  _  _  _  ♥ 5    _    _    _    _    _    _  _  _  _  _  _  _
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _    _    _    _    _    _  _  _  _  _  _  _
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _  _
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _    _    _    _    _    _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7    _    _    _    _  _  _  _  _  _  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

110.0 11.0 209.0
有效随机牌： 随机牌堆中 ♠ 10 可以移动去 下方牌堆 ♥ J 并且还有下方牌堆中♦ 9 可以移动到随机牌上
310.0 11.0 209.0
有效随机牌： 随机牌堆中 ♣ 10 可以移动去 下方牌堆 ♥ J 并且还有下方牌堆中♦ 9 可以移动到随机牌上
有几个动作 [(111, 1), (121, 1)]
移动随机牌堆里的牌
随机牌堆的♠ 10,移动到下方牌堆slot1 的牌 ♥ J 上


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7     8    9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♦ 9  ♣ 8   ♥ 7    _    _    _    _  _  _  _  _  _   
1  ♥ A    _    _  _  _  _  ♣ Q  ♥ J  ♠ 10    _    _    _    _  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _     _    _    _    _    _  _  _  _  _  _   
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _     _    _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7   ♥ 6  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _     _    _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8   ♠ 7    _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

普通移牌    ♦ 9 可以移动去 ♠ 10
有几个动作 [(0, 1)]
把solt 0 上的牌堆['♦ 9', '♣ 8', '♥ 7'] 移动到了 slot 1 上牌♠ 10


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7     8    9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _    _    _     _    _    _    _    _  _  _  _  _  _   
1  ♥ A    _    _  _  _  _  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _     _    _    _    _    _  _  _  _  _  _   
3  ♠ 6  ♦ K  ♠ 5  _  _  _  ♠ K    _     _    _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7   ♥ 6  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _     _    _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8   ♠ 7    _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

普通 K    ♠ K 可以移动去 _
有几个动作 [(3, 0)]
把solt 3 上的牌堆['♠ K'] 移动到了 slot 0 上牌_
把hide里的 slot3最外一张  ♠ 5  移动到了show的最上面一张 _


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7     8    9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K    _     _    _    _    _    _  _  _  _  _  _   
1  ♥ A    _    _  _  _  _  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7    _  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _     _    _    _    _    _  _  _  _  _  _   
3  ♠ 6  ♦ K    _  _  _  _  ♠ 5    _     _    _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7   ♥ 6  ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _     _    _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8   ♠ 7    _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  _  ♠ 4  ♦ A  ♣ A

None

表面牌的最后一张    ♠ 5   移动去已完成的牌堆里    ♠ 4
把hide里的 slot3最外一张  ♦ K  移动到了show的最上面一张 _
普通移牌    ♣ Q 可以移动去 ♦ K
有几个动作 [(1, 3)]
把solt 1 上的牌堆['♣ Q', '♥ J', '♠ 10', '♦ 9', '♣ 8', '♥ 7'] 移动到了 slot 3 上牌♦ K
把hide里的 slot1最外一张  ♥ A  移动到了show的最上面一张 _


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  ♥ 3  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K    _    _     _    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♥ A    _    _     _    _    _    _  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _    _     _    _    _    _  _  _  _  _  _   
3  ♠ 6    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5  ♥ 4  ♣ 3  ♥ 2  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  _  ♠ 5  ♦ A  ♣ A

None

表面牌的最后一张    ♥ A   移动去已完成的牌堆里    _
表面牌的最后一张    ♥ 2   移动去已完成的牌堆里    ♥ A
随机牌堆的  ♥ 3   已经移动到了已完成牌堆的    ♥ 2   里面了
普通 K    ♦ K 可以移动去 _
有几个动作 [(3, 1)]
把solt 3 上的牌堆['♦ K', '♣ Q', '♥ J', '♠ 10', '♦ 9', '♣ 8', '♥ 7'] 移动到了 slot 1 上牌_
把hide里的 slot3最外一张  ♠ 6  移动到了show的最上面一张 _


0  1  2    3     4  5    6    7  8  9   ... 14   15   16   17    18   19  \
0  _  _  _  ♥ 9  ♥ 10  _  ♥ Q  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J   

    20    21   22   23  
0  ♦ Q  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K    _    _     _    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _    _     _    _    _    _  _  _  _  _  _   
3    _    _    _  _  _  _  ♠ 6    _    _     _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5  ♥ 4  ♣ 3    _  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8  ♠ 7     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 3  ♠ 5  ♦ A  ♣ A

None

表面牌的最后一张    ♠ 6   移动去已完成的牌堆里    ♠ 5
表面牌的最后一张    ♠ 7   移动去已完成的牌堆里    ♠ 6
有几个动作 []
实在找不出了，找个深度最高的放进去了，开始搜索
随机牌堆除k以外都不能移动了
第0个-------------
♠ J
♥ 10
♠ 9
♦ 8
第1个-------------
{'♥ Q': 4.0, '♦ Q': 0.0}
[(106, 0)]
移动随机牌堆里的牌
随机牌堆的♥ Q,移动到下方牌堆slot0 的牌 ♠ K 上


0  1  2    3     4  5  6    7  8  9   ... 14   15   16   17    18   19   20  \
0  _  _  _  ♥ 9  ♥ 10  _  _  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J  ♦ Q   

     21   22   23  
0  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K  ♥ Q    _     _    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _    _     _    _    _    _  _  _  _  _  _   
3    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5  ♥ 4  ♣ 3    _  _  _  _  _  _   
5  ♦ 2  ♣ 2    _  _  _  _  ♠ 8    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8    _     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 3  ♠ 7  ♦ A  ♣ A

None

表面牌的最后一张    ♠ 8   移动去已完成的牌堆里    ♠ 7
把hide里的 slot5最外一张  ♣ 2  移动到了show的最上面一张 _
有几个动作 []
实在找不出了，找个深度最高的放进去了，开始搜索
随机牌堆除k以外都不能移动了
第0个-------------
♥ 10
♠ 9
♦ 8
第1个-------------
{'♠ J': 3.0, '♣ J': 0.0}
[(112, 0)]
移动随机牌堆里的牌
随机牌堆的♠ J,移动到下方牌堆slot0 的牌 ♥ Q 上


0  1  2    3     4  5  6    7  8  9   ... 14   15   16   17    18   19   20  \
0  _  _  _  ♥ 9  ♥ 10  _  _  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J  ♦ Q   

     21   22   23  
0  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K  ♥ Q  ♠ J     _    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _    _     _    _    _    _  _  _  _  _  _   
3    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5  ♥ 4  ♣ 3    _  _  _  _  _  _   
5  ♦ 2    _    _  _  _  _  ♣ 2    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8    _     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 3  ♠ 8  ♦ A  ♣ A

None

表面牌的最后一张    ♣ 2   移动去已完成的牌堆里    ♣ A
把hide里的 slot5最外一张  ♦ 2  移动到了show的最上面一张 _
普通移牌    ♦ 2 可以移动去 ♣ 3
有几个动作 [(5, 4)]
把solt 5 上的牌堆['♦ 2'] 移动到了 slot 4 上牌♣ 3


0  1  2    3     4  5  6    7  8  9   ... 14   15   16   17    18   19   20  \
0  _  _  _  ♥ 9  ♥ 10  _  _  ♥ K  _  _  ...  _  ♦ 3  ♦ 4  ♦ 5  ♦ 10  ♦ J  ♦ Q   

     21   22   23  
0  ♣ 10  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K  ♥ Q  ♠ J     _    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
2    _    _    _  _  _  _  ♥ 5    _    _     _    _    _    _  _  _  _  _  _   
3    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5  ♥ 4  ♣ 3  ♦ 2  _  _  _  _  _   
5    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8    _     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 3  ♠ 8  ♦ A  ♣ 2

None

表面牌的最后一张    ♦ 2   移动去已完成的牌堆里    ♦ A
表面牌的最后一张    ♣ 3   移动去已完成的牌堆里    ♣ 2
表面牌的最后一张    ♥ 4   移动去已完成的牌堆里    ♥ 3
随机牌堆的  ♦ 3   已经移动到了已完成牌堆的    ♦ 2   里面了
随机牌堆的  ♦ 4   已经移动到了已完成牌堆的    ♦ 3   里面了
随机牌堆的  ♦ 5   已经移动到了已完成牌堆的    ♦ 4   里面了
表面牌的最后一张    ♥ 5   移动去已完成的牌堆里    ♥ 4
10.0 111.0 109.0
有效随机牌： 随机牌堆中 ♥ 10 可以移动去 下方牌堆 ♠ J 并且还有下方牌堆中♠ 9 可以移动到随机牌上
210.0 111.0 109.0
有效随机牌： 随机牌堆中 ♦ 10 可以移动去 下方牌堆 ♠ J 并且还有下方牌堆中♠ 9 可以移动到随机牌上
有几个动作 [(104, 0), (118, 0)]
移动随机牌堆里的牌
随机牌堆的♥ 10,移动到下方牌堆slot0 的牌 ♠ J 上


0  1  2    3  4  5  6    7  8  9   ... 14 15 16 17    18   19   20    21  \
0  _  _  _  ♥ 9  _  _  _  ♥ K  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10   

    22   23  
0  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1    2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17  \
0    _    _    _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10    _    _    _  _  _  _  _  _   
1    _    _    _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _   
2    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
3    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
4  ♣ 4  ♦ 7    _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5    _    _    _  _  _  _  _  _   
5    _    _    _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _   
6  ♣ 9  ♣ 6  ♦ 6  _  _  _  ♠ 9  ♥ 8    _     _    _    _    _  _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 5  ♠ 8  ♦ 5  ♣ 3

None

普通移牌    ♠ 9 可以移动去 ♥ 10
有几个动作 [(6, 0)]
把solt 6 上的牌堆['♠ 9', '♥ 8'] 移动到了 slot 0 上牌♥ 10
把hide里的 slot6最外一张  ♦ 6  移动到了show的最上面一张 _


0  1  2    3  4  5  6    7  8  9   ... 14 15 16 17    18   19   20    21  \
0  _  _  _  ♥ 9  _  _  _  ♥ K  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10   

    22   23  
0  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1  2  3  4  5    6    7    8     9   10   11   12 13 14 15 16 17 18
0    _    _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8    _  _  _  _  _  _  _
1    _    _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  _  _  _  _  _  _
2    _    _  _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _  _
3    _    _  _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _  _
4  ♣ 4  ♦ 7  _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5    _    _    _  _  _  _  _  _  _
5    _    _  _  _  _  _    _    _    _     _    _    _    _  _  _  _  _  _  _
6  ♣ 9  ♣ 6  _  _  _  _  ♦ 6    _    _     _    _    _    _  _  _  _  _  _  _

0    1    2    3
0  ♥ 5  ♠ 8  ♦ 5  ♣ 3

None

表面牌的最后一张    ♦ 6   移动去已完成的牌堆里    ♦ 5
把hide里的 slot6最外一张  ♣ 6  移动到了show的最上面一张 _
普通移牌    ♣ 6 可以移动去 ♥ 7
有几个动作 [(6, 1)]
把solt 6 上的牌堆['♣ 6'] 移动到了 slot 1 上牌♥ 7
把hide里的 slot6最外一张  ♣ 9  移动到了show的最上面一张 _


0  1  2    3  4  5  6    7  8  9   ... 14 15 16 17    18   19   20    21  \
0  _  _  _  ♥ 9  _  _  _  ♥ K  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10   

    22   23  
0  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0    1  2  3  4  5    6    7    8     9   10   11   12   13 14 15 16 17  \
0    _    _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8    _    _  _  _  _  _   
1    _    _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  ♣ 6  _  _  _  _   
2    _    _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _   
3    _    _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _   
4  ♣ 4  ♦ 7  _  _  _  _  ♦ 8  ♣ 7  ♥ 6   ♣ 5    _    _    _    _  _  _  _  _   
5    _    _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _   
6    _    _  _  _  _  _  ♣ 9    _    _     _    _    _    _    _  _  _  _  _   

  18  
0  _  
1  _  
2  _  
3  _  
4  _  
5  _  
6  _

0    1    2    3
0  ♥ 5  ♠ 8  ♦ 6  ♣ 3

None

普通移牌    ♦ 8 可以移动去 ♣ 9
有几个动作 [(4, 6)]
把solt 4 上的牌堆['♦ 8', '♣ 7', '♥ 6', '♣ 5'] 移动到了 slot 6 上牌♣ 9
把hide里的 slot4最外一张  ♦ 7  移动到了show的最上面一张 _


0  1  2    3  4  5  6    7  8  9   ... 14 15 16 17    18   19   20    21  \
0  _  _  _  ♥ 9  _  _  _  ♥ K  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10   

    22   23  
0  ♣ J  ♣ K  

[1 rows x 24 columns]

None

0  1  2  3  4  5    6    7    8     9   10   11   12   13 14 15 16 17 18
0    _  _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8    _    _  _  _  _  _  _
1    _  _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  ♣ 6  _  _  _  _  _
2    _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
3    _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
4  ♣ 4  _  _  _  _  _  ♦ 7    _    _     _    _    _    _    _  _  _  _  _  _
5    _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
6    _  _  _  _  _  _  ♣ 9  ♦ 8  ♣ 7   ♥ 6  ♣ 5    _    _    _  _  _  _  _  _

0    1    2    3
0  ♥ 5  ♠ 8  ♦ 6  ♣ 3

None

表面牌的最后一张    ♦ 7   移动去已完成的牌堆里    ♦ 6
把hide里的 slot4最外一张  ♣ 4  移动到了show的最上面一张 _
有几个动作 []
实在找不出了，找个深度最高的放进去了，开始搜索
随机牌堆除k以外都不能移动了
第0个-------------
♠ Q
♦ J
♣ 10
♥ 9
第1个-------------
第2个-------------
第3个-------------
第4个-------------
第5个-------------
{'♥ K': 0.0, '♣ K': 0.0}
移动随机牌堆里的牌
随机牌堆的♥ K,移动到下方牌堆slot2 的牌 _ 上


0  1  2    3  4  5  6  7  8  9   ... 14 15 16 17    18   19   20    21   22  \
0  _  _  _  ♥ 9  _  _  _  _  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10  ♣ J   

    23  
0  ♣ K  

[1 rows x 24 columns]

None

0  1  2  3  4  5    6    7    8     9   10   11   12   13 14 15 16 17 18
0  _  _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8    _    _  _  _  _  _  _
1  _  _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  ♣ 6  _  _  _  _  _
2  _  _  _  _  _  _  ♥ K    _    _     _    _    _    _    _  _  _  _  _  _
3  _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
4  _  _  _  _  _  _  ♣ 4    _    _     _    _    _    _    _  _  _  _  _  _
5  _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
6  _  _  _  _  _  _  ♣ 9  ♦ 8  ♣ 7   ♥ 6  ♣ 5    _    _    _  _  _  _  _  _

0    1    2    3
0  ♥ 5  ♠ 8  ♦ 7  ♣ 3

None

表面牌的最后一张    ♣ 4   移动去已完成的牌堆里    ♣ 3
表面牌的最后一张    ♣ 5   移动去已完成的牌堆里    ♣ 4
表面牌的最后一张    ♥ 6   移动去已完成的牌堆里    ♥ 5
♠ Q 符合要求 下方牌堆两张同色 ♦ K ♥ K 1 2 上方随机牌堆有牌能直接放下来
有几个动作 [(113, 2)]
移动随机牌堆里的牌
随机牌堆的♠ Q,移动到下方牌堆slot2 的牌 ♥ K 上


0  1  2    3  4  5  6  7  8  9   ... 14 15 16 17    18   19   20    21   22  \
0  _  _  _  ♥ 9  _  _  _  _  _  _  ...  _  _  _  _  ♦ 10  ♦ J  ♦ Q  ♣ 10  ♣ J   

    23  
0  ♣ K  

[1 rows x 24 columns]

None

0  1  2  3  4  5    6    7    8     9   10   11   12   13 14 15 16 17 18
0  _  _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8    _    _  _  _  _  _  _
1  _  _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  ♥ 7  ♣ 6  _  _  _  _  _
2  _  _  _  _  _  _  ♥ K  ♠ Q    _     _    _    _    _    _  _  _  _  _  _
3  _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
4  _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
5  _  _  _  _  _  _    _    _    _     _    _    _    _    _  _  _  _  _  _
6  _  _  _  _  _  _  ♣ 9  ♦ 8  ♣ 7     _    _    _    _    _  _  _  _  _  _

0    1    2    3
0  ♥ 6  ♠ 8  ♦ 7  ♣ 5

None

表面牌的最后一张    ♣ 6   移动去已完成的牌堆里    ♣ 5
表面牌的最后一张    ♥ 7   移动去已完成的牌堆里    ♥ 6
表面牌的最后一张    ♣ 7   移动去已完成的牌堆里    ♣ 6
表面牌的最后一张    ♦ 8   移动去已完成的牌堆里    ♦ 7
♦ J 符合要求 下方牌堆两张同色 ♣ Q ♠ Q 1 2 上方随机牌堆有牌能直接放下来
有几个动作 [(119, 2)]
移动随机牌堆里的牌
随机牌堆的♦ J,移动到下方牌堆slot2 的牌 ♠ Q 上


0  1  2    3  4  5  6  7  8  9   ... 14 15 16 17    18 19   20    21   22  \
0  _  _  _  ♥ 9  _  _  _  _  _  _  ...  _  _  _  _  ♦ 10  _  ♦ Q  ♣ 10  ♣ J   

    23  
0  ♣ K  

[1 rows x 24 columns]

None

0  1  2  3  4  5    6    7    8     9   10   11 12 13 14 15 16 17 18
0  _  _  _  _  _  _  ♠ K  ♥ Q  ♠ J  ♥ 10  ♠ 9  ♥ 8  _  _  _  _  _  _  _
1  _  _  _  _  _  _  ♦ K  ♣ Q  ♥ J  ♠ 10  ♦ 9  ♣ 8  _  _  _  _  _  _  _
2  _  _  _  _  _  _  ♥ K  ♠ Q  ♦ J     _    _    _  _  _  _  _  _  _  _
3  _  _  _  _  _  _    _    _    _     _    _    _  _  _  _  _  _  _  _
4  _  _  _  _  _  _    _    _    _     _    _    _  _  _  _  _  _  _  _
5  _  _  _  _  _  _    _    _    _     _    _    _  _  _  _  _  _  _  _
6  _  _  _  _  _  _  ♣ 9    _    _     _    _    _  _  _  _  _  _  _  _

0    1    2    3
0  ♥ 7  ♠ 8  ♦ 8  ♣ 7

None

表面牌的最后一张    ♥ 8   移动去已完成的牌堆里    ♥ 7
表面牌的最后一张    ♠ 9   移动去已完成的牌堆里    ♠ 8
表面牌的最后一张    ♣ 8   移动去已完成的牌堆里    ♣ 7
表面牌的最后一张    ♦ 9   移动去已完成的牌堆里    ♦ 8
表面牌的最后一张    ♠ 10   移动去已完成的牌堆里    ♠ 9
表面牌的最后一张    ♣ 9   移动去已完成的牌堆里    ♣ 8
随机牌堆的  ♥ 9   已经移动到了已完成牌堆的    ♥ 8   里面了
随机牌堆的  ♦ 10   已经移动到了已完成牌堆的    ♦ 9   里面了
随机牌堆的  ♣ 10   已经移动到了已完成牌堆的    ♣ 9   里面了
随机牌堆的  ♣ J   已经移动到了已完成牌堆的    ♣ 10   里面了
表面牌的最后一张    ♥ 10   移动去已完成的牌堆里    ♥ 9
表面牌的最后一张    ♠ J   移动去已完成的牌堆里    ♠ 10
表面牌的最后一张    ♥ J   移动去已完成的牌堆里    ♥ 10
表面牌的最后一张    ♣ Q   移动去已完成的牌堆里    ♣ J
表面牌的最后一张    ♦ J   移动去已完成的牌堆里    ♦ 10
表面牌的最后一张    ♠ Q   移动去已完成的牌堆里    ♠ J
随机牌堆的  ♦ Q   已经移动到了已完成牌堆的    ♦ J   里面了
随机牌堆的  ♣ K   已经移动到了已完成牌堆的    ♣ Q   里面了
表面牌的最后一张    ♥ Q   移动去已完成的牌堆里    ♥ J
表面牌的最后一张    ♠ K   移动去已完成的牌堆里    ♠ Q
表面牌的最后一张    ♦ K   移动去已完成的牌堆里    ♦ Q
表面牌的最后一张    ♥ K   移动去已完成的牌堆里    ♥ Q
有几个动作 []
实在找不出了，找个深度最高的放进去了，开始搜索
随机牌堆除k以外都不能移动了
没有可以移动的了


0  1  2  3  4  5  6  7  8  9   ... 14 15 16 17 18 19 20 21 22 23
0  _  _  _  _  _  _  _  _  _  _  ...  _  _  _  _  _  _  _  _  _  _

[1 rows x 24 columns]

None

0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
0  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
1  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
2  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
3  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
4  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
5  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
6  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _

0    1    2    3
0  ♥ K  ♠ K  ♦ K  ♣ K

None

游戏成功
